# Generated by Django 3.1.3 on 2021-04-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200628_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hoel_image',
            new_name='hotel_image',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_reting',
            new_name='hotel_rating',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_delivery_boy_reting',
            new_name='user_delivery_boy_rating',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user_hotel_reting',
            new_name='user_hotel_rating',
        ),
    ]
